### ISSUE TITLE
Reordering

### ISSUE THREAD

**Issue by sgoodwin** [shrdev/Checklists#2]
Let's make it so that you can move items around in the list. I should be able to drag with my finger and move an item (this can be done in Edit mode).

**Comment by shrdev** [comment]
So the cell should be movable and have a delete functionality as well ?

**Comment by sgoodwin** [comment]
Indeed :)

**Comment by shrdev** [comment]
I have completed that task and created a PR..

**Comment by sgoodwin** [comment]
Cool! I made some comments on the PR.
