### ISSUE TITLE
Marking items as done

### ISSUE THREAD

**Issue by sgoodwin** [shrdev/Checklists#7]
Right now we can create and delete items, but it would be useful if we could mark an item as complete without deleting it. The text should show with a strikethrough or grayed-out text.

**Comment by shrdev** [comment]
I wrote this method. If someone tap on the cell it shows an alert. It is working fine until I add a new cell. Little help here 


`override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "checklistCell", for: indexPath) as! ChecklistTableViewCell
        let checklist = checklists[indexPath.row]
        cell.textEnteredLabel.text = checklist.text
        return cell
    }

 override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let alert = UIAlertController(title: "", message: "Mark as Completed", preferredStyle: .alert)
        let cancel = UIAlertAction(title: "cancel", style: .cancel, handler: nil)
        let ok = UIAlertAction(title: "Ok", style: .default) { (action: UIAlertAction) in
            let cell = tableView.cellForRow(at: indexPath)
            let label = cell?.viewWithTag(1000) as! UILabel
            let attributeString: NSMutableAttributedString =  NSMutableAttributedString(string: label.text!)
            attributeString.addAttribute(NSStrikethroughStyleAttributeName, value: 2, range: NSMakeRange(0, attributeString.length))
            label.attributedText = attributeString
        }
        alert.addAction(ok)
        alert.addAction(cancel)
        present(alert, animated: true, completion: nil)
    }`

**Comment by sgoodwin** [comment]
This updates the UI to show an item is done, but doesn't seem to update your model to actually record that information.
